language: minimal
sudo: false
notifications:
  email: false

matrix:
  fast_finish: true
  include:
  - env: CONDA_ENV=py37
  - env: CONDA_ENV=docs

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda info -a

install:
  - if [[ "$CONDA_ENV" == "docs" ]]; then
      conda env create -n test_env --file docs/environment.yml;
    else
      conda env create -n test_env --file ci/requirements-$CONDA_ENV.yml;
    fi;
  - conda activate test_env
  - conda list
  - python setup.py develop

script:
  - if [[ "$CONDA_ENV" == "docs" ]]; then
      sphinx-build -n -b html -d docs/build/doctrees docs/source docs/build/html;
    else
      pytest aeolus -c setup.cfg --flake8 --cov=aeolus --cov-config .coveragerc --cov-report term-missing -v;
    fi;

after_success:
  - if [[ "$CONDA_ENV" != "docs" ]]; then
      conda install conda-build anaconda-client;
      conda list;
      bash conda.recipe/conda_upload.sh;
    fi;
