name: aeolus_py37
channels:
- conda-forge
dependencies:
- python=3.7
- cached-property>=1.5.1
- cartopy
- dask
- f90nml
- flake8-builtins
- flake8-comprehensions
- flake8-copyright
- flake8-docstrings
- flake8-import-order
- flake8-mutable
- flake8-pep3101
- flake8-print
- flake8-quotes
- iris>=3.0
- latlon23
- matplotlib>=3.4
- numpy
- pep8-naming
- pip
- pytest>=2.4
- pytest-cov
- pytest-flake8
- python-stratify
