name: aeolus_test
channels:
- conda-forge
dependencies:
- python=3.11
- cached-property>=1.5.1
- cartopy
- click
- dask-core
- f90nml
- flake8-builtins
- flake8-comprehensions
- flake8-copyright
- flake8-docstrings
- flake8-import-order
- flake8-mutable
- flake8-pep3101
- flake8-print
- flake8-quotes
- iris>=3.4
- iris-esmf-regrid>=0.5
- latlon23
- loguru
- matplotlib>=3.6
- numpy
- pandas
- pep8-naming
- pip
- pytest>=3.3
- pytest-cov
- pytest-flake8
- python-stratify
- pip:
  - click_default_group
