name: aeolus_docs
channels:
- conda-forge
dependencies:
- python=3.9
- cached-property>=1.5.1
- cartopy
- f90nml
- ipython
- iris>=3.0
- latlon23
- matplotlib>=3.4
- nbsphinx
- numpy
- pip
- python-stratify
- pyvista
- sphinx
- sphinx_rtd_theme
