name: aeolus_docs
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - alabaster=0.7.12=py_0
  - antlr-python-runtime=4.7.2=py37_1000
  - appdirs=1.4.3=py_1
  - asn1crypto=1.2.0=py37_0
  - atomicwrites=1.3.0=py_0
  - attrs=19.3.0=py_0
  - babel=2.7.0=py_0
  - bleach=3.1.0=py_0
  - bokeh=1.3.4=py37_0
  - bzip2=1.0.8=h516909a_1
  - ca-certificates=2019.9.11=hecc5488_0
  - cartopy=0.17.0=py37h4331854_1007
  - certifi=2019.9.11=py37_0
  - cf-units=2.1.3=py37hc1659b7_0
  - cffi=1.13.1=py37h8022711_0
  - cftime=1.0.4.2=py37hc1659b7_0
  - chardet=3.0.4=py37_1003
  - click=7.0=py_0
  - cloudpickle=1.2.2=py_0
  - cryptography=2.7=py37h72c5cf5_0
  - curl=7.65.3=hf8cf82a_0
  - cycler=0.10.0=py_2
  - cytoolz=0.10.0=py37h516909a_0
  - dask=2.6.0=py_0
  - dask-core=2.6.0=py_0
  - dbus=1.13.6=he372182_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - distributed=2.6.0=py_0
  - docutils=0.15.2=py37_0
  - entrypoints=0.3=py37_1000
  - expat=2.2.5=he1b5a44_1004
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.0=he983fc9_1
  - fsspec=0.5.2=py_0
  - future=0.18.1=py37_0
  - geos=3.7.2=he1b5a44_2
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.58.3=h6f030ca_1002
  - gst-plugins-base=1.14.5=h0935bb2_0
  - gstreamer=1.14.5=h36ae1b5_0
  - hdf4=4.2.13=h9a582f1_1002
  - hdf5=1.10.5=nompi_h3c11f04_1104
  - heapdict=1.0.1=py_0
  - icu=64.2=he1b5a44_1
  - idna=2.8=py37_1000
  - imageio=2.6.1=py37_0
  - imagesize=1.1.0=py_0
  - importlib_metadata=0.23=py37_0
  - ipython_genutils=0.2.0=py_1
  - iris=2.2.1=py37_0
  - jinja2=2.10.3=py_0
  - jpeg=9c=h14c3975_1001
  - jsoncpp=1.8.4=hc9558a2_1001
  - jsonschema=3.1.1=py37_0
  - jupyter_core=4.5.0=py_0
  - kiwisolver=1.1.0=py37hc9558a2_0
  - krb5=1.16.3=h05b26f9_1001
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libcurl=7.65.3=hda55be3_0
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_2
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=14_openblas
  - libnetcdf=4.6.2=h303dfb8_1003
  - libopenblas=0.3.7=h6e990d7_2
  - libpng=1.6.37=hed695b0_0
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=hfc65ed5_1004
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=hee79883_5
  - locket=0.2.0=py_2
  - lz4-c=1.8.3=he1b5a44_1001
  - markupsafe=1.1.1=py37h14c3975_0
  - matplotlib=2.2.4=py37_1
  - matplotlib-base=2.2.4=py37h250f245_1
  - metpy=0.11.1=py37_0
  - mistune=0.8.4=py37h14c3975_1000
  - more-itertools=7.2.0=py_0
  - msgpack-python=0.6.2=py37hc9558a2_0
  - nbconvert=5.6.1=py37_0
  - nbformat=4.4.0=py_1
  - nbsphinx=0.4.3=py_0
  - ncurses=6.1=hf484d3e_1002
  - netcdf4=1.5.1.2=py37h73a1b54_1
  - numpy=1.17.3=py37h95a1406_0
  - olefile=0.46=py_0
  - openssl=1.1.1c=h516909a_0
  - owslib=0.18.0=py_0
  - packaging=19.2=py_0
  - pandas=0.25.2=py37hb3f55d8_0
  - pandoc=2.7.3=0
  - pandocfilters=1.4.2=py_1
  - partd=1.0.0=py_0
  - pcre=8.43=he1b5a44_0
  - pillow=6.2.1=py37h6b7be26_0
  - pint=0.9=py37_2
  - pip=19.3.1=py37_0
  - pluggy=0.13.0=py37_0
  - pooch=0.6.0=py37_0
  - proj4=6.1.1=hc80f0dc_1
  - psutil=5.6.3=py37h516909a_0
  - pthread-stubs=0.4=h14c3975_1001
  - py=1.8.0=py_0
  - pycparser=2.19=py37_1
  - pyepsg=0.4.0=py_0
  - pygments=2.4.2=py_0
  - pykdtree=1.3.1=py37h3010b51_1002
  - pyke=1.1.1=py37_1000
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.2=py_0
  - pyproj=2.3.1=py37h2fd02e8_0
  - pyqt=5.9.2=py37hcca6a23_4
  - pyrsistent=0.15.5=py37h516909a_0
  - pyshp=2.1.0=py_0
  - pysocks=1.7.1=py37_0
  - pytest=5.2.2=py37_0
  - python=3.7.3=h33d41f4_1
  - python-dateutil=2.8.0=py_0
  - pytz=2019.3=py_0
  - pyvista=0.22.4=py_0
  - pyyaml=5.1.2=py37h516909a_0
  - qt=5.9.7=h0c104cb_3
  - readline=8.0=hf8c457e_0
  - requests=2.22.0=py37_1
  - scipy=1.3.1=py37h921218d_2
  - scooby=0.4.3=py_0
  - setuptools=41.4.0=py37_0
  - shapely=1.6.4=py37hec07ddf_1006
  - sip=4.19.8=py37hf484d3e_1000
  - six=1.12.0=py37_1000
  - snowballstemmer=2.0.0=py_0
  - sortedcontainers=2.1.0=py_0
  - sphinx=2.2.1=py_0
  - sphinx_rtd_theme=0.4.3=py_0
  - sphinxcontrib-applehelp=1.0.1=py_0
  - sphinxcontrib-devhelp=1.0.1=py_0
  - sphinxcontrib-htmlhelp=1.0.2=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.2=py_0
  - sphinxcontrib-serializinghtml=1.1.3=py_0
  - sqlite=3.30.1=hcee41ef_0
  - tbb=2019.9=hc9558a2_0
  - tblib=1.4.0=py_0
  - testpath=0.4.2=py_1001
  - tk=8.6.9=hed695b0_1003
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py37h516909a_0
  - traitlets=4.3.3=py37_0
  - udunits2=2.2.27.6=h4e0c4b3_1001
  - urllib3=1.25.6=py37_0
  - vtk=8.2.0=py37hfdee58b_203
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - wheel=0.33.6=py37_0
  - xarray=0.14.0=py_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxt=1.2.0=h516909a_0
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - yaml=0.1.7=h14c3975_1001
  - zict=1.0.0=py_0
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.3=h3b9ef0a_0
  - pip:
    - latlon23==1.0.7
prefix: /local/denis/miniconda3/envs/aeolus_docs

